INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_PURELIQUID pureliquid)

FIND_PATH(
    PURELIQUID_INCLUDE_DIRS
    NAMES pureliquid/api.h
    HINTS $ENV{PURELIQUID_DIR}/include
        ${PC_PURELIQUID_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    PURELIQUID_LIBRARIES
    NAMES gnuradio-pureliquid
    HINTS $ENV{PURELIQUID_DIR}/lib
        ${PC_PURELIQUID_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(PURELIQUID DEFAULT_MSG PURELIQUID_LIBRARIES PURELIQUID_INCLUDE_DIRS)
MARK_AS_ADVANCED(PURELIQUID_LIBRARIES PURELIQUID_INCLUDE_DIRS)

